=== jeevesh-kaleeah/MoEvent/events1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

        <!-- Global image element -->
    <xs:element name="image">
        <xs:complexType>
            <xs:attribute name="cardImage">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".*\.jpg"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="backgroundImage">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".*\.jpg"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Root element -->
    <xs:element name="events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="type">
                                <!-- Restricting type using pattern -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="cinema|concert|theatre"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="genre" type="xs:string"/>
                            <xs:element name="date" type="xs:date"/>
                            <xs:element name="time" type="xs:time"/>
                            <xs:element name="info">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="duration" type="xs:string"/>
                                        <xs:element name="location" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="image"/>
                        </xs:sequence>
                        <!-- Event id attribute -->
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jeevesh-kaleeah/MoEvent/events1.xml
<?xml version="1.0" encoding="UTF-8"?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="events1.xsd">
    <event id="0">
        <name>avengers endgame</name>
        <type>cinema</type>
        <price>50</price>
        <genre>marvel</genre>
        <date>2024-10-01</date>
        <time>19:00</time>
        <info>
            <duration>1hr</duration>
            <location>bagatelle</location>
            <description>comedy movie about 3idiots trying to complete their engineering degree</description>
        </info>
        <image cardImage="endgame.jpg" backgroundImage="endgameposter.jpg" />
    </event>
    <event id="1">
        <name>barbie</name>
        <type>cinema</type>
        <price>30</price>
        <genre>melodrama</genre>
        <date>2024-10-05</date>
        <time>17:00</time>
        <info>
            <duration>1hr</duration>
            <location>bagatelle</location>
            <description>comedy movie about 3idiots trying to complete their engineering degree</description>
        </info>
        <image cardImage="Barbie.jpg" backgroundImage="Slide1.jpg" />
    </event>
    <event id="2">
        <name>avatar</name>
        <type>cinema</type>
        <price>30</price>
        <genre>science fiction</genre>
        <date>2024-10-05</date>
        <time>17:00</time>
        <info>
            <duration>1hr</duration>
            <location>bagatelle</location>
            <description>comedy movie about 3idiots trying to complete their engineering degree</description>
        </info>
        <image cardImage="avatar.jpg" backgroundImage="avatarposter.jpg" />
    </event>
    <event id="3">
        <name>jurassic</name>
        <type>cinema</type>
        <price>30</price>
        <genre>adventure</genre>
        <date>2024-10-05</date>
        <time>17:00</time>
        <info>
            <duration>1hr</duration>
            <location>bagatelle</location>
            <description>comedy movie about 3idiots trying to complete their engineering degree</description>
        </info>
        <image cardImage="jurassic.jpg" backgroundImage="jurassicposter.jpg" />
    </event>
    <event id="8">
        <name>lionking</name>
        <type>cinema</type>
        <price>30</price>
        <genre>emotional</genre>
        <date>2024-10-05</date>
        <time>17:00</time>
        <info>
            <duration>1hr</duration>
            <location>bagatelle</location>
            <description>comedy movie about 3idiots trying to complete their engineering degree</description>
        </info>
        <image cardImage="lionking.jpg" backgroundImage="lionkingposter.jpg" />
    </event>
    <!-- Add more events -->
</events>
